name: Terraform Plan (dev)

on:
  pull_request:
    paths:
      - 'envs/dev/**'
      - '**/*.tf'
      - '.github/workflows/**'

jobs:
  terraform-plan:
    uses: amithcm/eks-infra-pipeline/.github/workflows/terraform-plan.yaml@main
    with:
      workdir: envs/dev/ap-southeast-1
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION:   ${{ secrets.AWS_REGION }}
