---
name: Terraform Apply (dev)

on:
  push:
    branches:
      - main
    paths:
      - "envs/dev/**"
      - "**/*.tf"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform (dev)
    environment: dev
    uses: cmamith/eks-infra-pipeline/.github/workflows/terraform-apply-reusable.yml@main
    with:
      workdir: envs/dev/ap-southeast-1
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION:   ${{ secrets.AWS_REGION }}
